# This is a basic workflow to help you get started with Actions

name: Waka Readme

# Controls when the action will run. 
on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  #
  update-readme:
      name: Update Readme with Metrics
      runs-on: ubuntu-latest
      steps:
        - uses: anmol098/waka-readme-stats@master
          with:
            WAKATIME_API_KEY: "0036d259-c514-4bb8-a18f-25673e98d111"
            GH_TOKEN: "217be36b6640d50860a3aa7afa4c98542736374e"
            SHOW_OS: "True"
            SHOW_LANGUAGE: "True"
            SHOW_PROJECTS: "False"
            SHOW_EDITORS: "True"
